### PR TITLE
[#205] Update voting period in the Makefile from 11 seconds to 11 days

### LINKED ISSUE #205: Change the suggested voting period in the Makefile from 11 seconds to days
# Clarification and motivation

In the `Makefile` we have a default voting period of `11n`, since this value is in seconds, this is too low for a realistic use.

We should modify it to last a few days, probably 11 days would be a decent value.

Additionally, we should better document that "seconds" is the unit used here.

# Acceptance criteria

The default voting period length lasts at least a few days, the spec document clarifies that `voting_period` is a value expressed in seconds.

### PR DESCRIPTION
**Pull request by rinn7e**
## Description

Problem: In the `Makefile` we have a default voting period of `11n`,
since this value is in seconds, this is too low for a realistic use.

Solution: Update voting period in Makefile to 950400 seconds (11 days).

## Related issue(s)

Resolves #205 

#### Related changes (conditional)

- Tests
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

[//]: # (Add more docs here if you have them in the repository)
- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)
    - Haddock

#### Stylistic guide (mandatory)

- [x] My commits comply with [the following policy](https://www.notion.so/serokell/Commit-and-PR-policy-4cf98e1a910a415d86b5f2491d9af1af).
- [x] My code complies with the [style guide](../tree/master/docs/code-style.md).

### CODE REVIEW

**Review by pasqu4le — COMMENTED** [review]
The `docs/building.md` needs to be updated as well, as it says e.g.:
> All its arguments are optional and will be equal to the values above if not
specified.

But no list has been updated.

The rest LGTM

**Comment by pasqu4le** [comment]
Ah @rinn7e one last thing, in the description I mentioned that we should make sure that:
> he spec document clarifies that voting_period is a value expressed in seconds.

ATM the only place that says the value is in seconds is the Haskell code, I think we should add a comment in `types.mligo` too and mention at least once _somewhere_ in the `specification.md` the same thing.

**Comment by rinn7e** [comment]
> Ah @rinn7e one last thing, in the description I mentioned that we should make sure that:
> 
> > he spec document clarifies that voting_period is a value expressed in seconds.
> 
> ATM the only place that says the value is in seconds is the Haskell code, I think we should add a comment in `types.mligo` too and mention at least once _somewhere_ in the `specification.md` the same thing.

I add a type alias `second` and used it everywhere in the ligo files. Let me know if this is good enough.

**Review by pasqu4le — APPROVED** [review]
@rinn7e I think it works well, my only suggestion is to change it to `seconds`, plural.

**Pull request merged**
