### PR TITLE
[#119] Optimize compiled ligo contract

### LINKED ISSUE #119: Optimize LIGO contract using morley optimizer
# Clarification and motivation

We have an `optimize` command in `morley` that can make a Michelson contract a bit smaller. We'd like to use it because the smaller our contracts are, the better (as long as all the functionality is preserved).

# Acceptance criteria

LIGO version of BaseDAO that appears in build artifacts, releases and is passed to tests is optimized using `morley optimize`.

Note that we have an example in https://github.com/tqtezos/stablecoin.

### PR DESCRIPTION
**Pull request by rvem**
## Description
Problem: 'morley' has an option for contract optimization, which is
supposed to reduce contract size and its gas consumption.

Solution: Use 'morley optimize' for the compiled ligo contract, thus
we can test and provide optimized version of baseDAO contract.

## Related issue(s)

Resolves #119 

#### Related changes (conditional)

- Tests
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

[//]: # (Add more docs here if you have them in the repository)
- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)
    - Haddock

#### Stylistic guide (mandatory)

- [x] My commits comply with [the following policy](https://www.notion.so/serokell/Commit-and-PR-policy-4cf98e1a910a415d86b5f2491d9af1af).
- [x] My code complies with the [style guide](../tree/master/docs/code-style.md).

### CODE REVIEW

**Review by pasqu4le — COMMENTED** [review]
LGTM, but I'd like the optimization to happen in the `Makefile` as well.
Even tho it's not in the "acceptance criteria" I think it should be done here.

Specifically I'd say that we should make sure that `make test` (in `ligo/`) uses the optimized contract.
I think it would be better for the default `make` to not optimize it (so one can see the differences more easily if he makes changes) or to compile the non-optimized and optimized version separately.

**Comment by rvem** [comment]
That makes sense, will update the Makefile as well

**Comment by rvem** [comment]
@pasqu4le, I've updated `ligo/Makefile`, please check

**Review by pasqu4le — APPROVED** [review]
:ok_hand: LGTM.

It seems it managed to remove about ~150 bytes in origination costs :grin:

**Pull request merged**
