### PR TITLE
[#122] Enable weeder job

### LINKED ISSUE #122: Enable weeder job
# Clarification and motivation

In #110 we have temporarily disabled the `weeder` job on CI because it was tricky to fix that.

# Acceptance criteria

CI runs `weeder` again.

### PR DESCRIPTION
**Pull request by rinn7e**
## Description

Problem: In #110 we have temporarily disabled the `weeder` job on
CI because it was tricky to fix that.

Solution: Remove unneeded import, enable weeder job.

## Related issue(s)

Resolves #122 

#### Related changes (conditional)

- Tests
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

[//]: # (Add more docs here if you have them in the repository)
- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)
    - Haddock

#### Stylistic guide (mandatory)

- [x] My commits comply with [the following policy](https://www.notion.so/serokell/Commit-and-PR-policy-4cf98e1a910a415d86b5f2491d9af1af).
- [x] My code complies with the [style guide](../tree/master/docs/code-style.md).

### CODE REVIEW

**Review by gromakovsky — APPROVED** [review]
Oh, I actually promised to do it myself, but you did it before I got a chance :pensive: 

I've rebased it, hopefully CI will pass soon.

**Comment by gromakovsky** [comment]
@rinn7e I've pushed a few more commits, apparently now there are some additional unused dependencies, please check them out.

**Comment by rinn7e** [comment]
> Oh, I actually promised to do it myself, but you did it before I got a chance pensive
> 
> I've rebased it, hopefully CI will pass soon.

I was running out of issues yesterday, so I pick this one up. I've updated this now, let me know if it's good to merge this.

**Comment by gromakovsky** [comment]
Feel free to merge if CI passes.

**Comment by gromakovsky** [comment]
Oh, it passed. Alright, I am going to merge myself then :)

**Pull request merged**
